version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: alextldr-dot-com
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - GIN_MODE=release
        volumes:
            # Mount static assets for development
            - ./static:/root/static:ro
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:8080/",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # Development service with hot reload
    dev:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: alextldr-dot-com-dev
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - GIN_MODE=debug
        volumes:
            - .:/app
            - /app/node_modules
        working_dir: /app
        command: >
            sh -c "
              npm install &&
              npm run build-css-prod &&
              templ generate &&
              go run cmd/server/main.go
            "
        profiles:
            - dev
        depends_on: []

networks:
    default:
        name: alextldr-network
