/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./templates/**/*.{templ,go}",
        "./static/**/*.{html,js}",
        "./cmd/**/*.go",
        "./handlers/**/*.go",
        "./internal/**/*.go",
        "./services/**/*.go",
        "./models/**/*.go",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ["Inter", "system-ui", "sans-serif"],
            },
            animation: {
                "fade-in": "fadeIn 0.5s ease-in-out",
                "slide-up": "slideUp 0.5s ease-out",
            },
            keyframes: {
                fadeIn: {
                    "0%": { opacity: "0" },
                    "100%": { opacity: "1" },
                },
                slideUp: {
                    "0%": { transform: "translateY(20px)", opacity: "0" },
                    "100%": { transform: "translateY(0)", opacity: "1" },
                },
            },
        },
    },
    plugins: [require("@tailwindcss/typography"), require("daisyui")],
    daisyui: {
        themes: [
            {
                dracula: {
                    ...require("daisyui/src/theming/themes")["dracula"],
                    primary: "#ff79c6",
                    secondary: "#bd93f9",
                    accent: "#ffb86c",
                    neutral: "#414558",
                    "base-100": "#282a36",
                    "base-200": "#1e1f29",
                    "base-300": "#14151a",
                    info: "#8be9fd",
                    success: "#50fa7b",
                    warning: "#f1fa8c",
                    error: "#ff5555",
                },
            },
            "light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
            "dim",
            "nord",
            "sunset",
        ],
        darkTheme: "dracula",
        base: true,
        styled: true,
        utils: true,
        prefix: "",
        logs: true,
        themeRoot: ":root",
    },
};
