// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- About Section --><section id=\"about\" class=\"bg-base-100 py-16\"><div class=\"container mx-auto px-4\"><div class=\"text-center max-w-4xl mx-auto\"><!-- Profile Image with Fade Effect --><div class=\"avatar mb-8 transition-opacity duration-500\" x-data=\"{ scrollY: 0 }\" x-init=\"() => {\n\t\t\t\t\t\tconst updateScroll = () => scrollY = window.scrollY;\n\t\t\t\t\t\twindow.addEventListener('scroll', updateScroll);\n\t\t\t\t\t\tupdateScroll();\n\t\t\t\t\t}\" :style=\"`opacity: ${Math.max(0, 1 - scrollY / 100)}`\"><div class=\"w-32 h-32 rounded-full mx-auto border-4 border-primary\"><img src=\"/static/gopherAvatar.png\" alt=\"Alex's Avatar\" class=\"rounded-full\"></div></div><h1 class=\"text-5xl font-bold text-primary mb-8\">Hi there! I'm Alex</h1><p class=\"text-xl mb-6\">A Full Stack Developer with a strong focus on backend development in Go. I enjoy building clean, efficient solutions—whether it's with Go on the backend or Tailwind/templ/Alpine.js/HTMX on the frontend.</p><div class=\"divider\">Code by day, cartoons by night.</div><div class=\"text-center max-w-3xl mx-auto space-y-4\"><p class=\"text-lg\">I'm passionate about continuous learning and sharing knowledge. I lead the <a href=\"https://stuttgart-gophers.de/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"text-secondary\">Stuttgart Gophers meetup</a>, where we explore Go topics through talks, workshops, and discussions.</p><p class=\"text-lg\">Outside of coding, I'm into music, road trips, and biking. When I unwind, you'll usually find me watching The Simpsons, Futurama, or Rick and Morty, or diving into Football Manager to build my dream team.</p></div><div class=\"mt-8\"><a href=\"#cv\" class=\"btn btn-primary btn-lg\">Explore My Work</a></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
