// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func StuttgartGophers() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Stuttgart Gophers Section --><section id=\"stuttgart-gophers\" class=\"bg-base-200\"><div class=\"container mx-auto px-8 py-16\"><div class=\"text-center mb-8\"><h2 class=\"text-4xl font-bold text-primary mb-4\">Stuttgart Gophers</h2><p class=\"text-lg\">Leading the local Go community</p></div><div class=\"hero\"><div class=\"hero-content flex-col md:flex-row md:justify-between items-center w-full\"><!-- Left Gopher - Hidden on mobile, visible on md and up --><div class=\"hidden md:flex md:items-center\"><img src=\"/static/dancing-parrot.gif\" alt=\"Dancing Gopher\" class=\"w-24 h-24\"></div><!-- Center Content --><div class=\"max-w-3xl text-center\"><!-- Center Gopher - Visible on mobile, hidden on md and up --><div class=\"mb-6 md:hidden\"><img src=\"/static/dancing-parrot.gif\" alt=\"Dancing Gopher\" class=\"w-24 h-24 mx-auto\"></div><p class=\"text-lg mb-6\">In 2023, I was looking for Go meetups near Stuttgart but couldn't find any. So in December, I decided to start one myself. That's how the Stuttgart Gophers was born. We had our first online event in January 2024, and the group has been growing ever since. We're now over 250 members, and two members have joined me in helping organize things.<br>The goal is simple: bring Go enthusiasts together to learn, share ideas, and connect.</p><div class=\"flex justify-center space-x-4\"><a href=\"https://www.meetup.com/stuttgart-gophers\" target=\"_blank\" class=\"btn btn-primary\">Join Meetup</a> <a href=\"https://stuttgart-gophers.de\" target=\"_blank\" class=\"btn btn-outline btn-primary\">Browse Website</a></div></div><!-- Right Gopher - Hidden on mobile, visible on md and up --><div class=\"hidden md:flex md:items-center\"><img src=\"/static/dancing-parrot.gif\" alt=\"Dancing Gopher\" class=\"w-24 h-24\"></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
